select /*+ USE_NL(irf irfud irfug) USE_HASH(MAP1$scfg MAP2$scfg MAP3$scfg MAP4$scfg MAP5$scfg) */ dt.DATE_TIME_HOUR_KEY as DATE_TIME_KEY,
irf.TENANT_KEY as TENANT_KEY,
irf.RESOURCE_GROUP_COMBINATION_KEY as GROUP_COMBINATION_KEY,
irf.RESOURCE_KEY as RESOURCE_KEY,
irf.MEDIA_TYPE_KEY as MEDIA_TYPE_KEY,
irf.INTERACTION_TYPE_KEY as INTERACTION_TYPE_KEY,
irfud.INTERACTION_DESCRIPTOR_KEY as INTERACTION_DESCRIPTOR_KEY,
coalesce(-2,-2) as USER_DATA_KEY1,
coalesce(-2,-2) as USER_DATA_KEY2,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and af.FIRST_ENGAGE_FOR_AGENT_THRD = 1 then 1 else 0 end) as ACCEPTED_THREAD,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and af.FIRST_ENGAGE_FOR_AGENT_IXN = 1 then 1 else 0 end) as ACCEPTED_UNIQUE,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 then 1 else 0 end) as ACCEPTED,
sum(case when irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CUSTOMER_RING_COUNT > 0 then 1 else 0 end) as NOTACCEPTED,
sum(case when irf.CUSTOMER_DIAL_COUNT + irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_TALK_COUNT + irf.CUSTOMER_HANDLE_COUNT > 0 then 1 else 0 end) as OFFERED,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and af.FIRST_REPLY_FOR_AGENT_IXN = 1 then 1 else 0 end) as RESPONDED_UNIQUE,
sum(case when (mt.IS_ONLINE = 1 and irf.CUSTOMER_HANDLE_COUNT > 0) or (mt.IS_ONLINE = 0 and it.INTERACTION_SUBTYPE_CODE = 'OUTBOUNDREPLY' and td.TECHNICAL_RESULT_CODE = 'COMPLETED') then 1 else 0 end) as RESPONSES,
sum(case when irf.CUSTOMER_RING_COUNT > 0 and td.TECHNICAL_RESULT_CODE= 'CUSTOMERABANDONED' and td.RESULT_REASON_CODE= 'ABANDONEDWHILERINGING' then 1 else 0 end) as ABANDONED_INVITE,
sum(case when irf.CUSTOMER_RING_COUNT > 0 and irf.CUSTOMER_TALK_COUNT = 0 and td.TECHNICAL_RESULT_CODE= 'REDIRECTED' and td.RESOURCE_ROLE_CODE <> 'RECEIVEDCONSULT' then 1 else 0 end) as REJECTED,
sum(irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_DIAL_COUNT) as INVITE,
sum(irf.CUSTOMER_RING_DURATION + irf.CUSTOMER_DIAL_DURATION) as INVITE_TIME,
sum(irf.CUSTOMER_TALK_DURATION) as ENGAGE_TIME,
sum(irf.CUSTOMER_TALK_COUNT) as ENGAGE,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and (irf.CUSTOMER_TALK_DURATION <= scfg.INT_VAL_01 and scfg.INT_VAL_01 > 0) then irf.CUSTOMER_TALK_COUNT else 0 end) as SHORT,
sum(CUSTOMER_HOLD_DURATION) as HOLD_TIME,
sum(case when irf.CUSTOMER_HOLD_COUNT > 0 then 1 else 0 end) as HOLD,
sum(irf.CUSTOMER_ACW_DURATION) as WRAP_TIME,
sum(irf.CUSTOMER_ACW_COUNT) as WRAP,
sum(case when mt.IS_ONLINE = 1 and irf.CUSTOMER_HANDLE_COUNT = 0 then irf.CONS_RCV_TALK_DURATION + irf.TALK_DURATION + irf.POST_CONS_XFER_TALK_DURATION + irf.CONF_JOIN_TALK_DURATION when mt.IS_ONLINE = 0 then irf.CONS_RCV_TALK_DURATION else 0 end) as CONSULT_RECEIVED_ENGAGE_TIME,
sum(case when mt.IS_ONLINE = 1 and irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CONS_RCV_TALK_COUNT + irf.TALK_COUNT + irf.POST_CONS_XFER_TALK_COUNT + irf.CONF_JOIN_TALK_COUNT > 0 then 1 when mt.IS_ONLINE = 0 and it.INTERACTION_SUBTYPE_CODE <> 'INTERNALCOLLABORATIONREPLY' and irf.CONS_RCV_TALK_COUNT > 0 then 1 else 0 end) as CONSULT_RECEIVED_ACCEPTED,
sum(case when mt.IS_ONLINE = 1 and irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CONS_RCV_TALK_COUNT + irf.TALK_COUNT + irf.POST_CONS_XFER_TALK_COUNT + irf.CONF_JOIN_TALK_COUNT > 0 then 1 when mt.IS_ONLINE = 0 and it.INTERACTION_SUBTYPE_CODE = 'INTERNALCOLLABORATIONREPLY' and irf.CONS_RCV_TALK_COUNT > 0 and td.TECHNICAL_RESULT_CODE <> 'COMPLETED' then 1 else 0 end) as CONSULT_RESPONSES,
sum(case when irf.CUSTOMER_HANDLE_COUNT = 0 then irf.CONS_RCV_HOLD_DURATION + irf.HOLD_DURATION + irf.POST_CONS_XFER_HOLD_DURATION + irf.CONF_JOIN_HOLD_DURATION else 0 end) as CONSULT_RECEIVED_HOLD_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CONS_RCV_HOLD_COUNT + irf.HOLD_COUNT + irf.POST_CONS_XFER_HOLD_DURATION + irf.CONF_JOIN_HOLD_COUNT > 0 then 1 else 0 end) as CONSULT_RECEIVED_HOLD,
sum(case when irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CUSTOMER_RING_COUNT = 0 and td.RESOURCE_ROLE_CODE <> 'INITIATEDCONSULT' then irf.CONS_RCV_ACW_DURATION + irf.AFTER_CALL_WORK_DURATION else 0 end) as CONSULT_RECEIVED_WRAP_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT = 0 and irf.CUSTOMER_RING_COUNT = 0 and td.RESOURCE_ROLE_CODE <> 'INITIATEDCONSULT' and irf.CONS_RCV_ACW_COUNT + irf.AFTER_CALL_WORK_COUNT > 0 then 1 else 0 end) as CONSULT_RECEIVED_WRAP,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONS_RCV_TALK_COUNT > 0 then irf.CONS_RCV_TALK_DURATION else 0 end) as CONSULT_RCV_WARM_ENGAGE_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONS_RCV_TALK_COUNT > 0 then 1 else 0 end) as CONSULT_RCV_ACC_WARM,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONS_RCV_HOLD_COUNT > 0 then irf.CONS_RCV_HOLD_DURATION else 0 end) as CONSULT_RCV_WARM_HOLD_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONS_RCV_HOLD_COUNT > 0 then 1 else 0 end) as CONSULT_RCV_WARM_HOLD,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and td.RESOURCE_ROLE_CODE <> 'INITIATEDCONSULT' then irf.CONS_RCV_ACW_DURATION else 0 end) as CONSULT_RCV_WARM_WRAP_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and td.RESOURCE_ROLE_CODE <> 'INITIATEDCONSULT' and irf.CONS_RCV_ACW_DURATION > 0 then 1 else 0 end) as CONSULT_RCV_WARM_WRAP,
sum(case when ((mt.IS_ONLINE = 1 and td.TECHNICAL_RESULT_CODE not in ('TRANSFERRED' , 'CONFERENCED')) or (mt.IS_ONLINE = 0 and td.TECHNICAL_RESULT_CODE = 'TRANSFERRED')) and irf.CONS_INIT_TALK_COUNT + irf.CONS_INIT_HOLD_COUNT > 0 then 1 else 0 end) as CONSULT_INITIATED,
sum(case when (mt.IS_ONLINE = 1 and td.TECHNICAL_RESULT_CODE not in ('TRANSFERRED' , 'CONFERENCED')) or (mt.IS_ONLINE = 0 and td.TECHNICAL_RESULT_CODE = 'TRANSFERRED') then irf.CONS_INIT_TALK_DURATION + irf.CONS_INIT_HOLD_DURATION else 0 end) as CONSULT_INITIATED_TIME,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 then irf.CONFERENCE_INITIATED_COUNT else 0 end) as CONFERENCE_INITIATED,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and irf.CONF_JOIN_TALK_COUNT + irf.CONF_JOIN_HOLD_COUNT > 0 then 1 else 0 end) as CONFERENCE_RECEIVED_ACCEPTED,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and td.TECHNICAL_RESULT_CODE= 'TRANSFERRED' then 1 else 0 end) as TRANSFER_INIT_AGENT,
sum(case when irf.CUSTOMER_HANDLE_COUNT > 0 and td.RESOURCE_ROLE_CODE= 'RECEIVEDTRANSFER' then 1 else 0 end) as XFER_RECEIVED_ACCEPTED,
sum(case when irf.CUSTOMER_DIAL_COUNT + irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_TALK_COUNT + irf.CUSTOMER_HANDLE_COUNT > 0 and irfug.SATISFACTION is not null then 1 else 0 end) as SATISFACTION_OFFERED,
sum(case when irf.CUSTOMER_DIAL_COUNT + irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_TALK_COUNT + irf.CUSTOMER_HANDLE_COUNT > 0 then coalesce(cast(irfug.SATISFACTION as integer) , 0) else 0 end) as SATISFACTION,
sum(case when irf.CUSTOMER_DIAL_COUNT + irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_TALK_COUNT + irf.CUSTOMER_HANDLE_COUNT > 0 and irfug.REVENUE is not null then 1 else 0 end) as REVENUE_OFFERED,
sum(case when irf.CUSTOMER_DIAL_COUNT + irf.CUSTOMER_RING_COUNT + irf.CUSTOMER_TALK_COUNT + irf.CUSTOMER_HANDLE_COUNT > 0 then coalesce(cast(irfug.REVENUE as integer) , 0) else 0 end) as REVENUE,
sum(case when irf.STOP_ACTION = 1 then 1 else 0 end) as AGENT_DISCONNECT_FIRST
from INTERACTION_RESOURCE_FACT irf
inner join DATE_TIME  dt  on(irf.START_DATE_TIME_KEY = dt.DATE_TIME_KEY)
inner join TECHNICAL_DESCRIPTOR  td  on(irf.TECHNICAL_DESCRIPTOR_KEY = td.TECHNICAL_DESCRIPTOR_KEY)
left outer join ANCHOR_FLAGS  af  on(irf.ANCHOR_FLAGS_KEY = af.ANCHOR_FLAGS_KEY)
inner join MEDIA_TYPE  mt  on(mt.MEDIA_TYPE_KEY = irf.MEDIA_TYPE_KEY)
inner join INTERACTION_TYPE  it  on(it.INTERACTION_TYPE_KEY = irf.INTERACTION_TYPE_KEY)
left outer join AGR_SCFG_MAP MAP1$scfg on (MAP1$scfg.SCFG_TYPE_CODE='AGENT-IXN' and MAP1$scfg.SCFG_ORIGIN_SELECTOR='by-tenant-media' and MAP1$scfg.OBJ_ID=(irf.TENANT_KEY * 10000 + irf.MEDIA_TYPE_KEY))
left outer join AGR_SCFG_MAP MAP2$scfg on (MAP2$scfg.SCFG_TYPE_CODE='AGENT-IXN' and MAP2$scfg.SCFG_ORIGIN_SELECTOR='by-tenant' and MAP2$scfg.OBJ_ID=irf.TENANT_KEY)
left outer join AGR_SCFG_MAP MAP3$scfg on (MAP3$scfg.SCFG_TYPE_CODE='AGENT-IXN' and MAP3$scfg.SCFG_ORIGIN_SELECTOR='by-app-media' and MAP3$scfg.OBJ_ID=irf.MEDIA_TYPE_KEY)
left outer join AGR_SCFG_MAP MAP4$scfg on (MAP4$scfg.SCFG_TYPE_CODE='AGENT-IXN' and MAP4$scfg.SCFG_ORIGIN_SELECTOR='app-default' and MAP4$scfg.OBJ_ID=1)
left outer join AGR_SCFG_MAP MAP5$scfg on (MAP5$scfg.SCFG_TYPE_CODE='AGENT-IXN' and MAP5$scfg.SCFG_ORIGIN_SELECTOR='default' and MAP5$scfg.OBJ_ID=1)
inner join AGR_SCFG_SCHEDULE SCH$scfg on (SCH$scfg.SCFG_GROUP_KEY=coalesce(MAP1$scfg.SCFG_GROUP_KEY,MAP2$scfg.SCFG_GROUP_KEY,MAP3$scfg.SCFG_GROUP_KEY,MAP4$scfg.SCFG_GROUP_KEY,MAP5$scfg.SCFG_GROUP_KEY,-1) and SCH$scfg.END_DATE_TIME_KEY = 2147483647)
inner join AGR_SCFG scfg on (SCH$scfg.SCFG_KEY=scfg.SCFG_KEY)
inner join IRF_USER_DATA_KEYS  irfud  on(irf.INTERACTION_RESOURCE_ID = irfud.INTERACTION_RESOURCE_ID and irf.START_DATE_TIME_KEY = irfud.START_DATE_TIME_KEY)
inner join IRF_USER_DATA_GEN_1  irfug  on(irf.INTERACTION_RESOURCE_ID = irfug.INTERACTION_RESOURCE_ID and irf.START_DATE_TIME_KEY = irfug.START_DATE_TIME_KEY)
where irf.RESOURCE_KEY in (select r_.RESOURCE_KEY from RESOURCE_ r_ where r_.RESOURCE_TYPE_CODE not in ('ROUTINGPOINT' , 'QUEUE')) and not (irf.CONS_RCV_RING_DURATION > 0 and irf.CONS_RCV_TALK_COUNT + irf.CUSTOMER_RING_COUNT = 0) and not (irf.CUSTOMER_RING_COUNT = 0 and irf.RING_COUNT > 0 and irf.TALK_COUNT = 0) and not (irf.CONS_INIT_DIAL_COUNT > 0 and irf.CONS_INIT_TALK_COUNT = 0) and not (it.INTERACTION_SUBTYPE_CODE = 'INTERNALCOLLABORATIONREPLY' and irf.CONS_RCV_TALK_DURATION = 0)
    and dt.DATE_TIME_KEY = ?
group by dt.DATE_TIME_HOUR_KEY, irf.RESOURCE_GROUP_COMBINATION_KEY, irf.RESOURCE_KEY, irfud.INTERACTION_DESCRIPTOR_KEY, irf.TENANT_KEY, irf.MEDIA_TYPE_KEY, irf.INTERACTION_TYPE_KEY
